# Generated by Django 6.0.2 on 2026-05-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_insights', '0007_insightnotification_telegram_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightnotification',
            name='category',
            field=models.CharField(choices=[('daily_start', 'Daily start'), ('weekly_start', 'Weekly start'), ('daily_achievement', 'Daily summary'), ('weekly_achievement', 'Weekly achievement'), ('goal_due', 'Goal due'), ('goal_created', 'Goal created'), ('goal_completed', 'Goal completed'), ('course_completed', 'Course completed'), ('inactivity_warning', 'Inactivity warning')], max_length=32),
        ),
    ]
