# Generated by Django 6.0.2 on 2026-05-25 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_expand_filefield_paths'),
        ('students', '0004_alter_contentprogress_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='last_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumed_by_progress', to='courses.module'),
        ),
    ]
